### PR TITLE
Bump to v2.8.2

### PR DESCRIPTION
**Pull request by alicethorne-ab**
Bump to v2.8.2

### CODE REVIEW

**Comment by chasdl** [comment]
Can you verify a working `helm install` or `helm upgrade` using the packaged changes? i.e if you have a project called `op-scim-bridge`:

`helm upgrade op-scim-bridge op-scim-bridge-2.10.2.tgz`

**Comment by chasdl** [comment]
Should we update the packaged dependencies? i.e `helm dependency update charts/op-scim-bridge`

**Comment by alicethorne-ab** [comment]
Updated chart dependencies, and tested. All looks good. 👍🏻

**Comment by chasdl** [comment]
Thanks, @alicethorne-ab !

**Review by chasdl — APPROVED** [review]

**Pull request merged**
