### PR TITLE
Expand config options and documentation

### LINKED ISSUE #9: Update maintainer email address
We should update the maintainer email address from `support+business@1password.com` to `support+scim@1password.com`.

### LINKED ISSUE #21: Expand Supported Configuration Options
The current helm chart lacks the flexibility expected for doing deployments into custom clusters. The chart should be updated to include configuration values (and secure defaults) for:

- Annotations
- Node Selector definitions
- Pod Affinity definitions
- Desired number of instances
- Image Pull Policy
- Image Pull Secrets
- Security Context
- Resource limits for the pod
- Persistent Volume Storage Class name
- Liveness and Readiness Probes
- Configurable Redis Hostname
- Ingress Options
    - Current default is load balancer
    - Allow for ingress rules to be defined outside of this chart
- Configuration for TLS termination at Cluster ingress or Service
- Pod Tolerations
- Pod Disruption Budget

Examples of all these options can be seen in either the [Connect Helm Chart](https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/templates/connect-deployment.yaml) or [this closed PR](https://github.com/1Password/op-scim-helm/pull/5/files#diff-90f606e14abf95fb254de2a35f6ef6b6bc5701ccb706444a60ca16e88e994d24)

### LINKED ISSUE #22: Add option to store scimsession in Secret instead of Persistent Volume
By default the helm chart deploys the SCIM Bridge with a persistent volume claim to facilitate our various cloud provider marketplace 1-Click setup flow for providing the 1Password credentials to the server. Few cloud providers support `ReadWriteMany` as a method for persistent volume claims which prevents this chart being used for HA deployments, or zero downtime upgrades.

When using the chart directly we should provide options for the source of the volume mount instead of relying on the persistent volume for use cases where the deployment is not using the 1-Click setup. The volume mount could be via a K8s Secret resource created via the chart or via [Kubernetes Secrets Store CSI Driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver).

### LINKED ISSUE #24: Add documentation to the Chart
Currently there is no documentation in the chart. Documentation should include:

- Maintainer information
- Requirements of the Chart
- How to deploy the SCIM Bridge
- Supported Configuration Values (and their Default values)

See the [Connect Helm Chart for an example](https://github.com/1Password/connect-helm-charts/tree/main/charts/connect) or [this closed PR](https://github.com/1Password/op-scim-helm/pull/5/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

### LINKED ISSUE #27: Use .Chart.name instead of .Values.applicationName
We should prefer using the Chart name value instead of creating a separate entry in the `values.yaml` file.

Currently we use `applicationName` where we can directly use the name declared in the `Chart.yaml` file.

### PR DESCRIPTION
**Pull request by devillexio**
### Overview

In this PR we expand the options in `values.yaml` to make the configuration a bit more generic and easier to understand. We also add documentation `values.yaml` and the README.

Part of this work is also towards making the 1Password SCIM bridge Helm chart more deployment platform agnostic by removing platform-specific default options (such as `do-block-storage`).

The scope of this change turned out to be quite a bit more than I intended initially, so I have split off some of the work in follow up tickets, specifically:

- #29 
- #30 

### Related issues

- resolves #9 
- resolves #21
- resolves #22 
- resolves #24 
- resolves #27 

### Testing

I recommend we test by using this configuration to deploy to both Digital Ocean and GCP. Note that if you are deploying to DO you will need to set the `storageClass` option to `do-block-storage`.

The basic steps are:
1. Package: `helm package op-scim-bridge`
2. Install `helm install op-scim-bridge op-scim-2.3.0.tgz --create-namespace --namespace op-scim-bridge`

### CODE REVIEW

**Comment by devillexio** [comment]
Would love your input as well @ag-adampike. 🙏

**Comment by alicethorne-ab** [comment]
Gave it a once-over and it looks good to me. Much more readable. Good work!

**Review by alicethorne-ab — APPROVED** [review]

**Review by thatguygriff — APPROVED** [review]

**Comment by ag-adampike** [comment]
I had a look @devillexio, but your teammates are too fast and it’s already merged! 😅 

All looks good to me, but my Helming is still in its infancy. Nice to see the groundwork for supporting Ingress. Great work!

**Comment by devillexio** [comment]
No problem! Thank you for taking a look. My apologies for merging it before you provided feedback.

**Pull request merged**
