### PR TITLE
Bump to chart 2.10.4 for SCIM 2.8.3

### PR DESCRIPTION
**Pull request by chasdl**
## Overview

* Bumped to Helm chart `2.10.4` for SCIM bridge version `2.8.3`

## Changes

* Updated bitnami Redis and common dependancies
* Bump chart to 2.10.4 to pull in SCIM v2.8.3 (See [2.8.3 changelog](https://app-updates.agilebits.com/product_history/SCIM#v208031))

-----------------------------------------------------------------------

## Checklist

- [X] review the [guide to contributing](https://github.com/1Password/op-scim-helm/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by grellyd — APPROVED** [review]
LGTM! ✅ 

Don't forget to update the release notes once the release is formed via the GitHub Action.

**Comment by grellyd** [comment]
> Provide a detailed description of the changes, the problem that's being
addressed and how this is objectively a worthwhile addition to the project.

You probably don't need that in the overview 😉

**Comment by grellyd** [comment]
Suggested minor changes to the description:

 - Updated bitnami Redis and common dependancies
 - Bump chart to 2.10.4 to pull in SCIM v2.8.3 (See [2.8.3 changelog](https://app-updates.agilebits.com/product_history/SCIM#v208031))

**Comment by chasdl** [comment]
Oh boo my commits aren't being signed. New computer. ☹️

**Pull request merged**
