### PR TITLE
Bump to v2.6.0

### PR DESCRIPTION
**Pull request by alicethorne-ab**
## Overview

Bumps the SCIM bridge version to v2.6.0.

Tested using DO test account with Kubernetes.

See changelog here: https://app-updates.agilebits.com/product_history/SCIM

## Checklist

- [x] review the [guide to contributing](https://github.com/1Password/op-scim-helm/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by grellyd** [comment]
LGTM! ✅ 

I'll let Chas have a peek Monday before merging.

**Review by grellyd — APPROVED** [review]

**Comment by chasdl** [comment]
@alicethorne-ab Did we update the packaged dependency charts? i.e: 

`helm dependency update charts/op-scim-bridge`

When I ran this command it pulled down the latest charts that satisfy the dependencies.

**Comment by chasdl** [comment]
Verified the version bump works:

image

**Review by chasdl — APPROVED** [review]

**Comment by chasdl** [comment]
LGTM! ✅ Nice work!

**Pull request merged**
